### PR TITLE
Improve mongo connection with auth mechanism

### PR DESCRIPTION
**Pull request by yanmagale**
Hi guys.

I'm using this project with v3.2 of AdonisJS and i fouded this case:

> Using a auth mechanisms with mongo, its dont possible to connect in DB

I fix this problem checking especific fields in `.env` and include this information at `connectionQueryString`

### CODE REVIEW

**Comment by duyluonglc** [comment]
Hi @yanmagale 
Sorry for late response
Can you move `process.env.DB_AUTH_SOURCE` to `config.connection.auth` and modify the config file template?
if you use Adonis 3.2 you must use branch 1.x :)

**Comment by yanmagale** [comment]
Hi @duyluonglc , thanks for your feedback.

I will make changes and update a PR

**Comment by yanmagale** [comment]
I opened https://github.com/duyluonglc/lucid-mongo/pull/39 for support by adonis 3.2, with your suggestions @duyluonglc .

**Comment by yanmagale** [comment]
@duyluonglc would like that i make this changes at `dev` too ?

**Comment by duyluonglc** [comment]
yes man. The dev branch is v2
So please change the config template at ./templates/config.mustache too :)

**Comment by yanmagale** [comment]
I finished. Can you check this changes?

**Comment by duyluonglc** [comment]
Please remove trailing space
https://travis-ci.org/duyluonglc/lucid-mongo/jobs/283022690#L459

**Pull request merged**
